### ISSUE TITLE
Typo in the server addition form and YAML

### ISSUE THREAD

**Issue by dogukancagatay** [apigitlabs/apigit-support#27]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

There is a typo in the server addition form. The label of the variables section in the form is written as `Varibles` and the typo continues in the variables tree.

Unfortunately, the typo propagates to the YAML as well. When you add a server from the form, it is added to the YAML with `varibles` identifier.

### Steps To Reproduce

1. Edit a OpenAPI schema
2. Open `Servers` menu
3. Add a new server

### Screenshots or Videos

![Screenshot 2023-12-13 at 12 38 30](https://github.com/apigitlabs/apigit-support/assets/970872/df73b81d-7dc3-4040-bad7-1c1ca7f844af)

### Browser

Chrome

**Comment by apigitlabs** [comment]
thanks @dogukancagatay , the issue is fixed. please help to check ~

**Comment by dogukancagatay** [comment]
The issue seems partially fixed; the typo still exists in the variable specification part. Please see the screenshots.

The form:
<img width="1560" alt="Screenshot 2023-12-17 at 14 33 59" src="https://github.com/apigitlabs/apigit-support/assets/970872/755ed2f2-5032-406f-a88f-b662b4e117d3">

The YAML:
<img width="343" alt="Screenshot 2023-12-17 at 14 34 19" src="https://github.com/apigitlabs/apigit-support/assets/970872/dd4d977b-8b05-496e-bc8d-f762f31b2c1c">

**Comment by apigitlabs** [comment]
thanks @dogukancagatay , we identified the problem.  Team just fixed and deployed it in the weekend. Please help to check if it works in your side now.
